package minicla03.coinquylife.DATALAYER.remote.HouseSelectionAPI;

public enum SelectHouseStatus
{
    HOUSE_CREATED,
    HOUSE_NOT_FOUND,
    INVALID_CREDENTIALS,
    HOUSE_ALREADY_EXISTS,
    TOKEN_EXPIRED,
    TOKEN_INVALID,
    HOUSE_LOGGED_IN,
    HOUSE_NOT_CREATED, LINKED_SUCCES, USER_NOT_FOUND, LINKED_ERROR, ERROR, ALREADY_LINK, HOUSE_NAME_EMPTY, ALREADY_IN_HOUSE,
}
