package minicla03.coinquylife.DATALAYER.remote.AuthAPI;

public enum AuthStatus
{
    SUCCESS,
    USER_NOT_FOUND,
    WRONG_PASSWORD,
    NO_COINQUYHOUSE,
    HAS_COINQUYHOUSE,
    ERROR,
    AlREADY_REGISTERED,
    INVALID_EMAIL,
    INVALID_CREDENTIALS,
    USER_ALREADY_EXISTS,
    TOKEN_EXPIRED,
    TOKEN_INVALID,
    LINKED_ERROR, INVALID_PASSWORD,
}
